<?php/*
{"pPassword":"",
"pPasswordNew1":"",
"pPasswordNew2":"",
"sBlacklist":"",
"sHomepage":"..\/hover.php",
"sRoot":"..\/..\/source\/emanuelferu_hoverboard-firmware-hack-foc",
"sWhitelist":"",
"sWhitelistSave":"txt,log"}
*/?>