<?php/*
{"pPassword":"",
"pPasswordNew1":"",
"pPasswordNew2":"",
"sBlacklist":"",
"sHomepage":"homepage.php",
"sRootOrg":"CodeMirror\/..",
"sRootSave":"",
"sWhitelist":"",
"sWhitelistSave":"log,txt",
"sFiles":"{\"\\\/MinIDE.log\":[16,8,0],\"\\\/config.log\":[9,1,0]}"}
*/?>