<?php/*
{"pPassword":"",
"pPasswordNew1":"",
"pPasswordNew2":"",
"sBlacklist":"",
"sHomepage":"homepage.php",
"sRootOrg":"CodeMirror\/..",
"sRootSave":"",
"sWhitelist":"",
"sWhitelistSave":"log,txt"}
*/?>